import { Cell, BoardInterface } from "./interfaces"

export const PIECES = new Map<string, {description: string, codePoint: string}>([
  ['', { description: 'Empty cell', codePoint: '' }],

  ['WR1', { description: 'White Rook 1', codePoint: '\u2656' }],
  ['WN1', { description: 'White Knight 1', codePoint: '\u2658' }],
  ['WB1', { description: 'White Bishop 1', codePoint: '\u2657' }],
  ['WQ', { description: 'White Queen', codePoint: '\u2655' }],
  ['WK', { description: 'White King', codePoint: '\u2654' }],
  ['WB2', { description: 'White Bishop 2', codePoint: '\u2657' }],
  ['WN2', { description: 'White Knight 2', codePoint: '\u2658' }],
  ['WR2', { description: 'White Rook 2', codePoint: '\u2656' }],

  ['WP1', { description: 'White Pawn 1', codePoint: '\u2659' }],
  ['WP2', { description: 'White Pawn 2', codePoint: '\u2659' }],
  ['WP3', { description: 'White Pawn 3', codePoint: '\u2659' }],
  ['WP4', { description: 'White Pawn 4', codePoint: '\u2659' }],
  ['WP5', { description: 'White Pawn 5', codePoint: '\u2659' }],
  ['WP6', { description: 'White Pawn 6', codePoint: '\u2659' }],
  ['WP7', { description: 'White Pawn 7', codePoint: '\u2659' }],
  ['WP8', { description: 'White Pawn 8', codePoint: '\u2659' }],

  ['BP1', { description: 'Black Pawn 1', codePoint: '\u265F' }],
  ['BP2', { description: 'Black Pawn 2', codePoint: '\u265F' }],
  ['BP3', { description: 'Black Pawn 3', codePoint: '\u265F' }],
  ['BP4', { description: 'Black Pawn 4', codePoint: '\u265F' }],
  ['BP5', { description: 'Black Pawn 5', codePoint: '\u265F' }],
  ['BP6', { description: 'Black Pawn 6', codePoint: '\u265F' }],
  ['BP7', { description: 'Black Pawn 7', codePoint: '\u265F' }],
  ['BP8', { description: 'Black Pawn 8', codePoint: '\u265F' }],

  ['BR1', { description: 'Black Rook 1', codePoint: '\u265C' }],
  ['BN1', { description: 'Black Knight 1', codePoint: '\u265E' }],
  ['BB1', { description: 'Black Bishop 1', codePoint: '\u265D' }],
  ['BQ', { description: 'Black Queen', codePoint: '\u265B' }],
  ['BK', { description: 'Black King', codePoint: '\u265A' }],
  ['BB2', { description: 'Black Bishop 2', codePoint: '\u265D' }],
  ['BN2', { description: 'Black Knight 2', codePoint: '\u265E' }],
  ['BR2', { description: 'Black Rook 2', codePoint: '\u265C' }],
])

export const INITIAL_CELLS:Array<Cell> = [
  {ID: 'A8', pieceID: 'BR1', meta: { active: false, striped: false, movable: true }},
  {ID: 'B8', pieceID: 'BN1', meta: { active: false, striped: true, movable: true }},
  {ID: 'C8', pieceID: 'BB1', meta: { active: false, striped: false, movable: true }},
  {ID: 'D8', pieceID: 'BQ', meta: { active: false, striped: true, movable: true }},
  {ID: 'E8', pieceID: 'BK', meta: { active: false, striped: false, movable: true, }},
  {ID: 'F8', pieceID: 'BB2', meta: { active: false, striped: true, movable: true }},
  {ID: 'G8', pieceID: 'BN2', meta: { active: false, striped: false, movable: true, }},
  {ID: 'H8', pieceID: 'BR2', meta: { active: false, striped: true, movable: true }},

  {ID: 'A7', pieceID: 'BP1', meta: { active: false, striped: true, movable: true }},
  {ID: 'B7', pieceID: 'BP2', meta: { active: false, striped: false, movable: true }},
  {ID: 'C7', pieceID: 'BP3', meta: { active: false, striped: true, movable: true }},
  {ID: 'D7', pieceID: 'BP4', meta: { active: false, striped: false, movable: true }},
  {ID: 'E7', pieceID: 'BP5', meta: { active: false, striped: true, movable: true }},
  {ID: 'F7', pieceID: 'BP6', meta: { active: false, striped: false, movable: true }},
  {ID: 'G7', pieceID: 'BP7', meta: { active: false, striped: true, movable: true }},
  {ID: 'H7', pieceID: 'BP8', meta: { active: false, striped: false, movable: true }},

  {ID: 'A6', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'B6', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'C6', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'D6', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'E6', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'F6', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'G6', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'H6', pieceID: '', meta: { active: false, striped: true, movable: true }},

  {ID: 'A5', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'B5', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'C5', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'D5', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'E5', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'F5', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'G5', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'H5', pieceID: '', meta: { active: false, striped: false, movable: true }},

  {ID: 'A4', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'B4', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'C4', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'D4', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'E4', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'F4', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'G4', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'H4', pieceID: '', meta: { active: false, striped: true, movable: true }},

  {ID: 'A3', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'B3', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'C3', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'D3', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'E3', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'F3', pieceID: '', meta: { active: false, striped: false, movable: true }},
  {ID: 'G3', pieceID: '', meta: { active: false, striped: true, movable: true }},
  {ID: 'H3', pieceID: '', meta: { active: false, striped: false, movable: true }},

  {ID: 'A2', pieceID: 'WP1', meta: { active: false, striped: false, movable: true }},
  {ID: 'B2', pieceID: 'WP2', meta: { active: false, striped: true, movable: true }},
  {ID: 'C2', pieceID: 'WP3', meta: { active: false, striped: false, movable: true }},
  {ID: 'D2', pieceID: 'WP4', meta: { active: false, striped: true, movable: true }},
  {ID: 'E2', pieceID: 'WP5', meta: { active: false, striped: false, movable: true }},
  {ID: 'F2', pieceID: 'WP6', meta: { active: false, striped: true, movable: true }},
  {ID: 'G2', pieceID: 'WP7', meta: { active: false, striped: false, movable: true }},
  {ID: 'H2', pieceID: 'WP8', meta: { active: false, striped: true, movable: true }},

  {ID: 'A1', pieceID: 'WR1', meta: { active: false, striped: true, movable: true }},
  {ID: 'B1', pieceID: 'WN1', meta: { active: false, striped: false, movable: true }},
  {ID: 'C1', pieceID: 'WB1', meta: { active: false, striped: true, movable: true }},
  {ID: 'D1', pieceID: 'WQ', meta: { active: false, striped: false, movable: true }},
  {ID: 'E1', pieceID: 'WK', meta: { active: false, striped: true, movable: true }},
  {ID: 'F1', pieceID: 'WB2', meta: { active: false, striped: false, movable: true }},
  {ID: 'G1', pieceID: 'WN2', meta: { active: false, striped: true, movable: true }},
  {ID: 'H1', pieceID: 'WR2', meta: { active: false, striped: false, movable: true }},
]

export const INITIAL_BOARD:BoardInterface = {
  isWhitePlayerCurrent: true,
  cells: INITIAL_CELLS,
  moves: [],
  active: true,
  finalized: true
}
